"""
Django settings for mystor project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

from django.conf.global_settings import STATICFILES_DIRS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-^42afv-0!v==oxzonxyo!x_&(lxumr(cva_r1o4l56q+vz@9yi"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = 'RENDER' not in os.environ 

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "store",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mystor.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "store.custom_context_processor.categories_processor",  # إضافة معالج السياق المخصص هنا
                "store.custom_context_processor.cart_context",  # إضافة معالج السياق المخصص هنا
                "store.custom_context_processor.wishlist_context",  # إضافة معالج السياق المخصص هنا
            ],
        },
    },
]

WSGI_APPLICATION = "mystor.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        # إذا لم يجد قاعدة بيانات خارجية، يستخدم SQLite المحلية
        default='sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3'),
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


MEDIA_URL = "/media/"
MEDIA_ROOT = "media/"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'
# STATICFILES_DIRS = [BASE_DIR, os.path.join(BASE_DIR, 'staticfiles')]
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = "/dist/"
STATICFILES_DIRS = [BASE_DIR / "dist"]  # هذا يشير إلى مجلد static الموجود في مشروعك
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Session configuration
SESSION_ENGINE = "django.contrib.sessions.backends.db"  # حفظ الجلسات في قاعدة البيانات
SESSION_COOKIE_AGE = 86400  # الجلسة تنتهي بعد 24 ساعة (بالثواني)
SESSION_COOKIE_HTTPONLY = True  # منع الوصول إلى الكوكي من JavaScript (للمزيد من الأمان)
SESSION_SAVE_EVERY_REQUEST = True  # حفظ الجلسة في كل طلب (مهم جداً!)
SESSION_COOKIE_SAMESITE = "Lax"  # حماية CSRF
SESSION_COOKIE_SECURE = False  # False في التطوير، True في الإنتاج (HTTPS)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # الجلسة لا تنتهي عند إغلاق المتصفح


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
