# Generated by Django 5.2.8 on 2025-11-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorymovement',
            options={'verbose_name': 'حركة مخزون', 'verbose_name_plural': 'المخزون'},
        ),
        migrations.AlterModelOptions(
            name='specification',
            options={'verbose_name': 'الوصف', 'verbose_name_plural': 'المواصفات'},
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
