# Generated by Django 5.2.8 on 2025-11-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_inventorymovement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.JSONField(blank=True, help_text='أدخل المميزات كقائمة JSON، مثال: [{"icon": "fa-microchip", "text": "معالج قوي"}]', null=True),
        ),
    ]
